export const districts = [
  { key: "1", value: "Jaffna" },
  { key: "2", value: "Kilinochchi" },
  { key: "3", value: "Mannar" },
  { key: "4", value: "Mullaitivu" },
  { key: "5", value: "Vavuniya" },
  { key: "6", value: "Puttalam" },
  { key: "7", value: "Kurunegala" },
  { key: "8", value: "Gampaha" },
  { key: "9", value: "Colombo" },
  { key: "10", value: "Kalutara" },
  { key: "11", value: "Anuradhapura" },
  { key: "12", value: "Polonnaruwa" },
  { key: "13", value: "Matale" },
  { key: "14", value: "Kandy" },
  { key: "15", value: "Nuwaraeliya" },
  { key: "16", value: "Kegalle" },
  { key: "17", value: "Ratnapura" },
  { key: "18", value: "Trincomalee" },
  { key: "19", value: "Batticaloa" },
  { key: "20", value: "Ampara" },
  { key: "21", value: "Badulla" },
  { key: "22", value: "Monaragala" },
  { key: "23", value: "Hambantota" },
  { key: "24", value: "Matara" },
  { key: "25", value: "Galle" },
];

export const universities = [
  { key: "1", value: "University of Colombo", district: "9" },
  { key: "2", value: "University of Peradeniya", district: "14" },
  { key: "3", value: "University of Kelaniya", district: "8" },
  { key: "4", value: "University of Moratuwa", district: "9" },
  { key: "5", value: "University of Jaffna", district: "1" },
  { key: "6", value: "University of Sri Jayewardenepura", district: "9" },
  { key: "7", value: "University of Vavuniya", district: "5" },
  { key: "8", value: "University of Ruhuna", district: "24" },
  { key: "9", value: "Eastern University of Sri Lanka", district: "19" },
  { key: "10", value: "Rajarata University of Sri Lanka", district: "11" },
  { key: "11", value: "Sabaragamuwa University of Sri Lanka", district: "17" },
  {
    key: "12",
    value: " South Eastern University of Sri Lanka",
    district: "20",
  },
  { key: "13", value: "Uva Wellassa University", district: "20" },
  { key: "14", value: "Wayamba University of Sri Lanka", district: "7" },
];

export const categories = [
  ["1", "Architecture and engineering"],
  ["2", "Arts, culture and entertainment"],
  ["3", "Business, management and administration"],
  ["4", "Communications"],
  ["5", "Community and social services"],
  ["6", "College/University Student"],
  ["7", "Education"],
  ["8", "Science and technology"],
  ["9", "Installation, repair and maintenance"],
  ["10", "Farming, fishing and forestry"],
  ["11", "Health and medicine"],
  ["12", "Law and public policy"],
  ["13", "Hospitality, Travel and Tourism"],
];
export const faculties = [
  "Medicine",
  "Engineering",
  "Physical Science",
  "Biological Science",
  "Accounting and Management",
  "Statistics",
  "Arts",
];
